name: Generate EPG
on:
  schedule:
    - cron: '00 13 * * *'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  check-run:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.check_local_time.outputs.run }}
    steps:
      - name: check timezone
        id: check_tz
        env:
          TRIGGER: ${{ github.event_name }}
        run: |
          echo "Trigger: ${TRIGGER}"
          if [[ ${TRIGGER} == 'schedule' ]]; then
            echo "Checking daylight saving time"
            if [ $(date --date='TZ="Asia/Jakarta" now' +%H) -eq '13' ]; then
              echo 'Time to run!'
              echo "run=True" >> "$GITHUB_OUTPUT"
            else
              echo "It's not 13:00 local time in Asia/Jakarta. Waiting for next execution..."
              echo "run=False" >> "$GITHUB_OUTPUT"
            fi
          else
            echo 'Trigger is not cron, ommiting time check!'
            echo "run=True" >> "$GITHUB_OUTPUT"
          fi

  my-job:
    runs-on: ubuntu-latest
    if: needs.check-run.outputs.run == 'True'
    needs: check-run
      - name: checkout repo
        uses: actions/checkout@v2
      - name: config
        run: |
          git pull
          git config --global user.email "reinmclaren33@gmail.com"
          git config --global user.name "Faizal Hamzah"
      - name: update streams
        run: |
          cd epg
          pwd
          pip install lxml
          echo "Generating EPG for main playlist..."
          python3 scripts/index.py guide.xml scripts/general.txt "12537.stream.ip.tv Playlist" http://103.152.118.53
          tar -czvf guide.xml.gz guide.xml
          rm guide.xml
          echo "Generating EPG for local playlist..."
          python3 scripts/index.py guide.xml scripts/local.txt "12537.stream.ip.tv Playlist" http://103.152.118.53
          cd ..
      - name: commit
        run: |
          git add -A
          git commit -m "Generate EPG every day at 1.00pm JKT (13.00 WIB)"
          git push
