# This is a basic workflow to help you get started with Actions

name: Generate EPG

# Controls when the action will run. 
on:
  schedule:
    - cron: '00 13 * * *'

  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo testing!

      # Runs a set of commands using the runners shell 
      - name: git config
        run: |
          git pull
          git config --global user.email "reinmclaren33@gmail.com"
          git config --global user.name "Faizal Hamzah"

      - name: token
        env:
          AUTH: ${{ secrets.AUTH }}

      - name: update streams
        run: |
          cd epg
          pwd
          pip install lxml
          echo "Generating EPG for main playlist..."
          python3 scripts/index.py guide.xml scripts/general.txt "12537.stream.ip.tv Playlist" https://12537-stream-ip-tv.xyz
          tar -czvf guide.xml.gz guide.xml
          rm guide.xml
          echo "Generating EPG for local playlist..."
          python3 scripts/index.py guide.xml scripts/local.txt "12537.stream.ip.tv Playlist" https://12537-stream-ip-tv.xyz
          cd ..

      - name: git add
        run: |
          git add -A
          ls -la
          git commit -m "Generate EPG every 1.00pm"

      - name: git commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force-push: true
