name: Generate EPG every day
on:
  schedule:
    - cron: '00 00-12/6 * * *'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: config
        run: |
          git pull
          git config --global user.email "reinmclaren33@gmail.com"
          git config --global user.name "Faizal Hamzah"
      - name: generate
        run: |
          cd epg
          pwd
          [ ! -d global ] && mkdir -v global/
          [ ! -d local ] && mkdir -v local/
          python3 -m pip install lxml pgzip
          echo "Generating EPG..."
          python3 scripts/index.py -o guide.xml --source="scripts/global/global.txt" --gen-name="Libretelevision" --gen-url="https://libretv.my.id/" --compress
          mv -v guide.xml.gz global/
          cd ..
      - name: commit
        run: |
          git add -A
          git commit -m "Generate EPG every day"
          git push
