name: Generate EPG every day
on:
  schedule:
    - cron: '00 00-12/6 * * *'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: config
        run: |
          git pull
          git config --global user.email "reinmclaren33@gmail.com"
          git config --global user.name "Faizal Hamzah"
      - name: generate
        run: |
          cd epg
          pwd
          mkdir output
          echo "Installing dependencies..."
          python3 -m pip install lxml pgzip requests
          echo "Generating EPG..."
          python3 -u <(wget -qO- -U okhttp/5.0 --no-check-certificate https://libretv.my.id/assets/python/epg.py) -zo output/guide.xml --source="scripts/global/global.txt" --gen-name="Libretelevision" --gen-url="libretv.my.id"
          mv -v output/guide.xml.gz .
          rm -rf output
          cd ..
      - name: commit
        run: |
          git add -A
          git commit -m "Generate EPG every day"
          git push
