name: Update Other streams
on:
  schedule:
    - cron: '00 00/2 * * *'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: config
        run: |
          git pull
          git config --global user.email "reinmclaren33@gmail.com"
          git config --global user.name "Faizal Hamzah"
      - name: update streams
        run: |
          pwd
          mkdir tmp
          wget -U 'okhttp/1.2' -qP tmp http://103.152.118.53:80/api/pidio/index.py
          python3 tmp/index.py --channel-code 7464 --channel-name "ajwa-tv" ajewa.m3u8
          python3 tmp/index.py --channel-code 7052 --channel-name "hip-hip-horee" hiphiphore.m3u8
          python3 tmp/index.py --channel-code 7946 --channel-name "tv-tempo" tempo.m3u8
          python3 tmp/index.py --channel-code 6898 --channel-name "u-channel" yucenel.m3u8
          python3 tmp/index.py --channel-code 8237 --channel-name "mentari-tv" mentariteve.m3u8
          rm -rf tmp
      - name: commit
        run: |
          git add -A
          git commit -m "Update streams"
          git push
